# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    sgcl.admin.category.company:
        class: AppBundle\Admin\CompanyAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Personal Data", label: "Compañía" }
        arguments:
            - ~
            - AppBundle\Entity\Company
            - ~
        calls:
            - [ setTranslationDomain, [AppBundle]]
    sgcl.admin.category.trademark:
        class: AppBundle\Admin\TrademarkAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Personal Data", label: "Marca" }
        arguments:
            - ~
            - AppBundle\Entity\Trademark
            - ~
        calls:
            - [ setTranslationDomain, [AppBundle]]
    sgcl.admin.category.barcode:
        class: AppBundle\Admin\BarcodeAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Personal Data", label: "Código de barras" }
        arguments:
            - ~
            - AppBundle\Entity\Barcode
            - AppBundle:BarcodeCRUD
        calls:
            - [ setTranslationDomain, [AppBundle]]
            - [ setTemplate, [edit, Barcode/CRUD/base_edit.html.twig] ]
            - [ setTemplate, [show, Barcode/CRUD/base_show.html.twig] ]
    sgcl.admin.category.table_logistic_variables:
        class: AppBundle\Admin\TableLogisticVariablesAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Personal Data", label: "Tabla de variables logísticas" }
        arguments:
            - ~
            - AppBundle\Entity\TableLogisticVariables
            - ~
        calls:
            - [ setTranslationDomain, [AppBundle]]
    sgcl.admin.category.product:
        class: AppBundle\Admin\ProductAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Personal Data", label: "Producto" }
        arguments:
            - ~
            - AppBundle\Entity\Product
            - AppBundle:ProductCRUD
        calls:
            - [ setTranslationDomain, [AppBundle]]
            - [ setTemplate, [edit, Product/CRUD/base_edit.html.twig] ]
            - [ setTemplate, [show, Product/CRUD/base_show.html.twig] ]
