# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    sgcl.admin.category:
        class: AppBundle\Admin\CompanyAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Personal Data", label: "Company" }
        arguments:
            - ~
            - AppBundle\Entity\Company
            - ~
        calls:
            - [ setTranslationDomain, [AppBundle]]