# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    sgcl.admin.category.company:
        class: AppBundle\Admin\CompanyAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Personal Data", label: "Company" }
        arguments:
            - ~
            - AppBundle\Entity\Company
            - ~
        calls:
            - [ setTranslationDomain, [AppBundle]]
    sgcl.admin.category.trademark:
        class: AppBundle\Admin\TrademarkAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Personal Data", label: "Trademark" }
        arguments:
            - ~
            - AppBundle\Entity\Trademark
            - ~
        calls:
            - [ setTranslationDomain, [AppBundle]]
    sgcl.admin.category.barcode:
        class: AppBundle\Admin\BarcodeAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Personal Data", label: "Barcode" }
        arguments:
            - ~
            - AppBundle\Entity\Barcode
            - ~
        calls:
            - [ setTranslationDomain, [AppBundle]]
    sgcl.admin.category.tableLogisticVariables:
            class: AppBundle\Admin\TableLogisticVariablesAdmin
            tags:
                - { name: sonata.admin, manager_type: orm, group: "Personal Data", label: "TableLogisticVarialbes" }
            arguments:
                - ~
                - AppBundle\Entity\TableLogisticVariables
                - ~
            calls:
                - [ setTranslationDomain, [AppBundle]]
    sgcl.admin.category.product:
                class: AppBundle\Admin\ProductAdmin
                tags:
                    - { name: sonata.admin, manager_type: orm, group: "Personal Data", label: "Product" }
                arguments:
                    - ~
                    - AppBundle\Entity\Product
                    - AppBundle:ProductCRUD
                calls:
                    - [ setTranslationDomain, [AppBundle]]
                    - [ setTemplate, [edit, Product/CRUD/base_edit.html.twig]]
