sonata_admin:
    title: SGCL
#    title_logo:
    options:
        html5_validate:     true
        use_icheck:         false

    templates:
        # default global templates
        # the layout template include javascript/stylesheet to the formatter bundle,
        # if you don't need it use the default one: SonataAdminBundle::standard_layout.html.twig
        layout:  standard_layout.html.twig
        ajax:    SonataAdminBundle::ajax_layout.html.twig

        # default value if done set, actions templates, should extends a global templates
        list:    SonataAdminBundle:CRUD:list.html.twig
        show:    SonataAdminBundle:CRUD:show.html.twig
        edit:    SonataAdminBundle:CRUD:edit.html.twig

    dashboard:
#        blocks:
        groups:
            sgcl.admin.group.administration:
                label:           sonata_administration
                label_catalogue: SonataAdminBundle
                icon:            '<i class="fa fa-cogs"></i>'
                items:
                    - sonata.user.admin.user
                    - sonata.user.admin.group

            sgcl.admin.group.management:
                label:           Gestión
                label_catalogue: AppBundle
                icon:            '<i class="fa fa-sitemap"></i>'
                items:
                    - sgcl.admin.category.company
                    - sgcl.admin.category.trademark
                    - sgcl.admin.category.barcode
                    - sgcl.admin.category.table_logistic_variables
                    - sgcl.admin.category.product
#    assets:
#        stylesheets:
#        javascripts:
