<?php
/**
 * Created by PhpStorm.
 * User: jmb
 * Date: 28/02/15
 * Time: 20:10
 */

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TrademarkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BarcodeRepository extends EntityRepository
{
}
