<?php
/**
 * Created by PhpStorm.
 * User: jmb
 * Date: 14/02/15
 * Time: 19:06
 */

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CompanyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrademarkRepository extends EntityRepository
{
}
